### ISSUE TITLE
generate-odata-client cause uncaughtException: Cannot find module 'execa'

### ISSUE THREAD

**Issue by nazarkulyk** [SAP/cloud-sdk#559]
After update to 1.29.0 version i get an error on generating odata client localy with npm.

1. create package.json like that:

```json
{
  "name": "xxx",
  "version": "1.0.4",
  "private": true,
  "dependencies": {
    "@sap-cloud-sdk/core": "^1.29.0",
    "@sap-cloud-sdk/generator": "^1.29.0"
  },
  "scripts": {
    "generate": "generate-odata-client -i service --outputDir ./ --versionInPackageJson=1.0.4 --forceOverwrite"
  },
  "devDependencies": {},
  "engines": {
    "node": "^12.14.0",
    "npm": "^6.14.0"
  }
}
```

2. execute npm i && npm run generate
3. See error

```bash
2020-10-08T08:46:31.343Z] ERROR    uncaughtException: Cannot find module 'execa'
Require stack:
- /Users/odata-example/node_modules/@sap-cloud-sdk/generator/dist/generator.js
- /Users/odata-example/node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js
Error: Cannot find module 'execa'
Require stack:
- /Users/odata-example/node_modules/@sap-cloud-sdk/generator/dist/generator.js
- /Users/odata-example/node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:747:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/odata-example/node_modules/@sap-cloud-sdk/generator/dist/generator.js:47:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

Workarround is to add execa to dependencies. But please correct this dependancy on generator package

```json
"dependencies": {
    "execa": "^4.0.3",
    "@sap-cloud-sdk/core": "^1.29.0",
    "@sap-cloud-sdk/generator": "^1.29.0"
  }
```

**Comment by marikaner** [comment]
@nazarkulyk Thanks for pointing that out. I will fix this right away.

**Comment by marikaner** [comment]
@nazarkulyk Just out of curiosity, which version did you use before?

**Comment by nazarkulyk** [comment]
I think, @marikaner, there is one more dependancy if you enable Typedoc generation:

```bash
"generateTypedocJson": "true"
```

**Comment by nazarkulyk** [comment]
> @nazarkulyk Just out of curiosity, which version did you use before?

1.28.1

**Comment by marikaner** [comment]
Hey @nazarkulyk,

Version 1.30.0 was released with a fix for this yesterday. Let us know if this is still an issue.
